# streamlit/dockerfile

# Use a imagem Python específica (versão 3.12)
FROM python:3.12.5-slim

# Defina o diretório de trabalho
WORKDIR /app

# Copie o arquivo de dependências
COPY requirements.txt .

# Instale as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copie o código da aplicação
COPY . .

# Exponha a porta usada pelo Streamlit
EXPOSE 8501

# Execute a aplicação Streamlit
CMD ["streamlit", "run", "streamlit_app.py", "--server.enableCORS=false", "--server.port=8501"]
