# api/Dockerfile

# Use uma imagem Python específica (versão 3.12)
FROM python:3.12.5-slim

# Defina o diretório de trabalho
WORKDIR /app

# Copie o arquivo de dependências
COPY requirements.txt .

# Instale as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copie o código da aplicação
COPY . .

# Exponha a porta usada pela API Flask
EXPOSE 5000

# Execute a aplicação Flask
CMD ["python", "api.py"]
